# Generated by Django 6.0.3 on 2026-03-10 04:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiQuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_quy', models.CharField(max_length=100, verbose_name='Tên quỹ')),
                ('is_khoa_so', models.BooleanField(default=False, verbose_name='Khóa sổ kế toán')),
            ],
            options={
                'verbose_name': 'Loại quỹ',
                'verbose_name_plural': '2. Quản lý Đa Quỹ',
            },
        ),
        migrations.CreateModel(
            name='MucTieuQuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_muc_tieu', models.CharField(max_length=255, verbose_name='Tên mục tiêu')),
                ('so_tien_muc_tieu', models.BigIntegerField(verbose_name='Số tiền mục tiêu (VNĐ)')),
                ('so_tien_hien_tai', models.BigIntegerField(default=0, verbose_name='Đã gom được (VNĐ)')),
                ('hoan_thanh', models.BooleanField(default=False, verbose_name='Đã hoàn thành?')),
            ],
            options={
                'verbose_name': 'Mục Tiêu Quỹ',
                'verbose_name_plural': 'Các Mục Tiêu Quỹ',
            },
        ),
        migrations.CreateModel(
            name='SuKienNhacViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_su_kien', models.CharField(max_length=255, verbose_name='Tên sự kiện')),
                ('mo_ta', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mô tả ngắn')),
                ('ngay_dien_ra', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày diễn ra')),
            ],
            options={
                'verbose_name': 'Sự Kiện & Nhắc Việc',
                'verbose_name_plural': 'Danh Sách Sự Kiện',
                'ordering': ['ngay_dien_ra'],
            },
        ),
        migrations.CreateModel(
            name='TaiSan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_tai_san', models.CharField(max_length=200, verbose_name='Tên tài sản')),
                ('gia_mua', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá mua')),
                ('ngay_mua', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày mua')),
                ('ti_le_khau_hao', models.FloatField(default=10, verbose_name='% Khấu hao/Năm')),
            ],
            options={
                'verbose_name': 'Tài sản',
                'verbose_name_plural': '4. Quản lý Tài sản & Khấu hao',
            },
        ),
        migrations.CreateModel(
            name='ThanhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('mssv', models.CharField(max_length=20, unique=True, verbose_name='MSSV')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('is_no_xau', models.BooleanField(default=False, verbose_name='Nợ xấu/Bảo lưu')),
            ],
            options={
                'verbose_name': 'Thành viên',
                'verbose_name_plural': '1. Danh sách Thành viên',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('role', models.CharField(choices=[('ADMIN', 'Thủ Quỹ (Lớp trưởng)'), ('MEMBER', 'Thành Viên')], default='MEMBER', max_length=10)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('mssv', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mã sinh viên')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='quanlyquy_user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='quanlyquy_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DotThu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dot', models.CharField(max_length=200, verbose_name='Tên đợt thu')),
                ('so_tien_moi_nguoi', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Định mức nộp')),
                ('han_chot', models.DateField(verbose_name='Hạn chót')),
                ('loai_quy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlyquy.loaiquy', verbose_name='Vào quỹ')),
            ],
            options={
                'verbose_name': 'Đợt thu',
                'verbose_name_plural': '3. Các Đợt thu tiền',
            },
        ),
        migrations.CreateModel(
            name='GiaoDich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai', models.CharField(choices=[('THU', 'Thu quỹ'), ('CHI', 'Chi quỹ'), ('TU', 'Tạm ứng'), ('HU', 'Hoàn ứng'), ('LAI', 'Lãi ngân hàng'), ('NB', 'Điều chuyển nội bộ')], max_length=3, verbose_name='Loại giao dịch')),
                ('so_tien', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền')),
                ('ly_do', models.CharField(max_length=255, verbose_name='Nội dung')),
                ('anh_hoa_don', models.ImageField(blank=True, null=True, upload_to='hoadon/', verbose_name='Hóa đơn')),
                ('ngay_tao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày giao dịch')),
                ('dot_thu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanlyquy.dotthu', verbose_name='Đợt thu')),
                ('loai_quy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlyquy.loaiquy', verbose_name='Quỹ')),
                ('thanh_vien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanlyquy.thanhvien', verbose_name='Thành viên')),
            ],
            options={
                'verbose_name': 'Giao dịch',
                'verbose_name_plural': '5. Lịch sử Giao dịch',
            },
        ),
    ]
