# Generated by Django 6.0.3 on 2026-03-11 02:52

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('quanlyquy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BieuQuyet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm')),
                ('cau_hoi', models.CharField(max_length=255, verbose_name='Câu hỏi biểu quyết')),
                ('han_chot', models.DateTimeField(verbose_name='Hạn chót vote')),
                ('dang_mo', models.BooleanField(default=True, verbose_name='Đang diễn ra')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaiDatHeThong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm')),
                ('ma_cai_dat', models.CharField(max_length=100, unique=True, verbose_name='Mã (VD: MUC_PHAT_TRE)')),
                ('gia_tri', models.CharField(max_length=255, verbose_name='Giá trị')),
                ('mo_ta', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DanhMucThuChi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm')),
                ('ten_danh_muc', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('loai', models.CharField(choices=[('THU', 'Thu'), ('CHI', 'Chi')], max_length=3, verbose_name='Loại')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HuyHieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm')),
                ('ten_huy_hieu', models.CharField(max_length=100, verbose_name='Tên Huy hiệu')),
                ('link_icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Icon/Emoji')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('diem_yeu_cau', models.IntegerField(default=0, verbose_name='Điểm yêu cầu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LichSuWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm')),
                ('ma_giao_dich_ngan_hang', models.CharField(max_length=100, unique=True)),
                ('so_tien', models.DecimalField(decimal_places=0, max_digits=12)),
                ('raw_payload', models.JSONField(verbose_name='Dữ liệu JSON gốc từ NH')),
                ('trang_thai_xu_ly', models.BooleanField(default=False, verbose_name='Đã gạch nợ tự động chưa?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='dotthu',
            options={},
        ),
        migrations.AlterModelOptions(
            name='giaodich',
            options={},
        ),
        migrations.AlterModelOptions(
            name='loaiquy',
            options={},
        ),
        migrations.AlterModelOptions(
            name='muctieuquy',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sukiennhacviec',
            options={},
        ),
        migrations.AlterModelOptions(
            name='taisan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='thanhvien',
            options={},
        ),
        migrations.AddField(
            model_name='dotthu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 11, 2, 50, 51, 416252, tzinfo=datetime.timezone.utc), verbose_name='Ngày tạo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dotthu',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)'),
        ),
        migrations.AddField(
            model_name='dotthu',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm'),
        ),
        migrations.AddField(
            model_name='dotthu',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối'),
        ),
        migrations.AddField(
            model_name='dotthu',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)'),
        ),
        migrations.AddField(
            model_name='giaodich',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 11, 2, 52, 20, 770060, tzinfo=datetime.timezone.utc), verbose_name='Ngày tạo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='giaodich',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)'),
        ),
        migrations.AddField(
            model_name='giaodich',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm'),
        ),
        migrations.AddField(
            model_name='giaodich',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối'),
        ),
        migrations.AddField(
            model_name='giaodich',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)'),
        ),
        migrations.AddField(
            model_name='loaiquy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 11, 2, 52, 23, 245018, tzinfo=datetime.timezone.utc), verbose_name='Ngày tạo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loaiquy',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)'),
        ),
        migrations.AddField(
            model_name='loaiquy',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm'),
        ),
        migrations.AddField(
            model_name='loaiquy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối'),
        ),
        migrations.AddField(
            model_name='loaiquy',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)'),
        ),
        migrations.AddField(
            model_name='muctieuquy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 11, 2, 52, 24, 955731, tzinfo=datetime.timezone.utc), verbose_name='Ngày tạo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='muctieuquy',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)'),
        ),
        migrations.AddField(
            model_name='muctieuquy',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm'),
        ),
        migrations.AddField(
            model_name='muctieuquy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối'),
        ),
        migrations.AddField(
            model_name='muctieuquy',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)'),
        ),
        migrations.AddField(
            model_name='sukiennhacviec',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 11, 2, 52, 26, 558337, tzinfo=datetime.timezone.utc), verbose_name='Ngày tạo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sukiennhacviec',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)'),
        ),
        migrations.AddField(
            model_name='sukiennhacviec',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm'),
        ),
        migrations.AddField(
            model_name='sukiennhacviec',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối'),
        ),
        migrations.AddField(
            model_name='sukiennhacviec',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)'),
        ),
        migrations.AddField(
            model_name='taisan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 11, 2, 52, 28, 221895, tzinfo=datetime.timezone.utc), verbose_name='Ngày tạo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taisan',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)'),
        ),
        migrations.AddField(
            model_name='taisan',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm'),
        ),
        migrations.AddField(
            model_name='taisan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối'),
        ),
        migrations.AddField(
            model_name='taisan',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)'),
        ),
        migrations.AddField(
            model_name='thanhvien',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 11, 2, 52, 29, 807311, tzinfo=datetime.timezone.utc), verbose_name='Ngày tạo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thanhvien',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)'),
        ),
        migrations.AddField(
            model_name='thanhvien',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm'),
        ),
        migrations.AddField(
            model_name='thanhvien',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối'),
        ),
        migrations.AddField(
            model_name='thanhvien',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)'),
        ),
        migrations.AddField(
            model_name='thanhvien',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='credit_score',
            field=models.IntegerField(default=100, verbose_name='Điểm tín nhiệm'),
        ),
        migrations.AlterField(
            model_name='giaodich',
            name='loai',
            field=models.CharField(choices=[('THU', 'Thu quỹ'), ('CHI', 'Chi quỹ'), ('TU', 'Tạm ứng'), ('HU', 'Hoàn ứng'), ('LAI', 'Lãi NH'), ('NB', 'Điều chuyển nội bộ')], max_length=3, verbose_name='Loại giao dịch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='HoaDonChungTu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm')),
                ('link_anh', models.ImageField(upload_to='chung_tu/', verbose_name='Ảnh chứng từ')),
                ('ai_doc_so_tien', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('ai_doc_noi_dung', models.CharField(blank=True, max_length=255, null=True)),
                ('giao_dich', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quanlyquy.giaodich', verbose_name='Giao dịch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HuyHieuThanhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm')),
                ('ngay_dat_duoc', models.DateTimeField(default=django.utils.timezone.now)),
                ('huy_hieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlyquy.huyhieu')),
                ('thanh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlyquy.thanhvien')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KhieuNai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm')),
                ('tieu_de', models.CharField(max_length=255, verbose_name='Vấn đề')),
                ('noi_dung', models.TextField(verbose_name='Chi tiết')),
                ('trang_thai', models.CharField(choices=[('MO', 'Đang mở'), ('DANG_XU_LY', 'Đang xử lý'), ('DONG', 'Đã giải quyết')], default='MO', max_length=20)),
                ('thanh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlyquy.thanhvien', verbose_name='Người khiếu nại')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BinhLuanKhieuNai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm')),
                ('noi_dung', models.TextField()),
                ('nguoi_binh_luan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('khieu_nai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binh_luan', to='quanlyquy.khieunai')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KhoanNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm')),
                ('so_tien', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền nợ')),
                ('loai_no', models.CharField(max_length=50, verbose_name='Loại nợ')),
                ('han_chot', models.DateField(blank=True, null=True, verbose_name='Hạn chót')),
                ('da_hoan_thanh', models.BooleanField(default=False, verbose_name='Đã trả xong')),
                ('thanh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlyquy.thanhvien', verbose_name='Người nợ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LuaChonBieuQuyet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm')),
                ('noi_dung_lua_chon', models.CharField(max_length=255, verbose_name='Lựa chọn')),
                ('bieu_quyet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_lua_chon', to='quanlyquy.bieuquyet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LuotBinhChon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm')),
                ('bieu_quyet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlyquy.bieuquyet')),
                ('lua_chon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlyquy.luachonbieuquyet')),
                ('thanh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlyquy.thanhvien')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NhatKyHeThong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hanh_dong', models.CharField(max_length=50, verbose_name='Hành động')),
                ('ten_bang', models.CharField(max_length=100, verbose_name='Bảng bị tác động')),
                ('du_lieu_cu', models.JSONField(blank=True, null=True, verbose_name='Dữ liệu cũ')),
                ('du_lieu_moi', models.JSONField(blank=True, null=True, verbose_name='Dữ liệu mới')),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('nguoi_dung', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhieuDeXuatChi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm')),
                ('so_tien', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền cần xin')),
                ('muc_dich', models.TextField(verbose_name='Mục đích chi')),
                ('trang_thai', models.CharField(choices=[('CHO_DUYET', 'Chờ duyệt'), ('DA_DUYET', 'Đã duyệt'), ('TU_CHOI', 'Từ chối')], default='CHO_DUYET', max_length=20)),
                ('nguoi_de_xuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlyquy.thanhvien', verbose_name='Người xin chi')),
                ('nguoi_duyet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phieu_da_duyet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm')),
                ('tieu_de', models.CharField(max_length=255)),
                ('noi_dung', models.TextField()),
                ('da_doc', models.BooleanField(default=False)),
                ('thanh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlyquy.thanhvien')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TienDoDongQuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm')),
                ('so_tien_can_nop', models.DecimalField(decimal_places=0, max_digits=12)),
                ('so_tien_da_nop', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('duoc_mien_giam', models.BooleanField(default=False)),
                ('trang_thai', models.CharField(choices=[('CHUA_NOP', 'Chưa nộp'), ('THIEU', 'Nộp thiếu'), ('DU', 'Đã đủ')], default='CHUA_NOP', max_length=20)),
                ('dot_thu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlyquy.dotthu')),
                ('thanh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlyquy.thanhvien')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
