# Generated by Django 6.0.3 on 2026-03-11 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyquy', '0002_bieuquyet_caidathethong_danhmucthuchi_huyhieu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giaodich',
            name='is_an_danh',
            field=models.BooleanField(default=False, verbose_name='Giao dịch ẩn danh'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Thủ Quỹ (Lớp trưởng)'), ('MEMBER', 'Thành Viên'), ('TESTER', 'QA/Tester')], default='MEMBER', max_length=10),
        ),
        migrations.CreateModel(
            name='BugBounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm')),
                ('mo_ta_loi', models.TextField(verbose_name='Mô tả lỗi từ Frontend')),
                ('trang_thai', models.CharField(choices=[('PENDING', 'Chờ kiểm chứng'), ('FIXED', 'Đã xác nhận & Cấp Xu'), ('REJECTED', 'Báo cáo sai')], default='PENDING', max_length=20)),
                ('xu_thuong', models.IntegerField(default=0, verbose_name='Xu thưởng hệ thống')),
                ('nguoi_bao_cao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người báo lỗi')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QATestingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_test', models.CharField(max_length=100, verbose_name='Kịch bản giả lập (VD: ROT_MANG_BANK)')),
                ('du_lieu_phat_sinh', models.JSONField(verbose_name='Dữ liệu Data-Seed (Auto generate)')),
                ('trang_thai', models.CharField(default='SUCCESS', max_length=50)),
                ('thoi_gian_test', models.DateTimeField(auto_now_add=True)),
                ('nguoi_test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThoaThuanBaoMat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm')),
                ('dong_y_dieu_khoan', models.BooleanField(default=False, verbose_name='Đã đồng ý PDPA')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP lúc xác nhận')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
