# Generated by Django 6.0.3 on 2026-03-11 09:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyquy', '0003_giaodich_is_an_danh_alter_user_role_bugbounty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugbounty',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bugbounty',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bugbounty',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='bugbounty',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='bugbounty',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='bugbounty',
            name='xu_thuong',
        ),
        migrations.AddField(
            model_name='bugbounty',
            name='ngay_tao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 11, 9, 36, 45, 843503, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bugbounty',
            name='mo_ta_loi',
            field=models.TextField(verbose_name='Mô tả lỗi'),
        ),
        migrations.AlterField(
            model_name='bugbounty',
            name='nguoi_bao_cao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bugbounty',
            name='trang_thai',
            field=models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('FIXED', 'Đã sửa - Đã cấp Xu'), ('REJECTED', 'Báo cáo sai')], default='PENDING', max_length=20),
        ),
    ]
