# Generated by Django 6.0.3 on 2026-03-11 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyquy', '0004_remove_bugbounty_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhiemVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm')),
                ('tieu_de', models.CharField(max_length=200)),
                ('phan_thuong_xu', models.IntegerField(default=10)),
                ('da_hoan_thanh', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuaTang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm')),
                ('ten_qua', models.CharField(max_length=255, verbose_name='Tên món quà')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả đặc quyền')),
                ('gia_xu', models.IntegerField(default=0, verbose_name='Giá đổi (Xu)')),
                ('so_luong_kho', models.IntegerField(default=10, verbose_name='Số lượng còn lại')),
                ('icon', models.CharField(default='fa-gift', max_length=50, verbose_name='Icon FontAwesome')),
                ('mau_sac', models.CharField(default='#C8A8E9', max_length=20, verbose_name='Mã màu UI (Hex)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LichSuDoiQua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm')),
                ('trang_thai', models.CharField(choices=[('CHO_NHAN', 'Chờ nhận'), ('DA_GIAO', 'Đã giao')], default='CHO_NHAN', max_length=20)),
                ('thanh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlyquy.thanhvien')),
                ('qua_tang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlyquy.quatang')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
