# Generated by Django 6.0.3 on 2026-03-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyquy', '0005_nhiemvu_quatang_lichsudoiqua'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhiemvu',
            name='da_hoan_thanh',
        ),
        migrations.RemoveField(
            model_name='nhiemvu',
            name='phan_thuong_xu',
        ),
        migrations.RemoveField(
            model_name='nhiemvu',
            name='tieu_de',
        ),
        migrations.AddField(
            model_name='nhiemvu',
            name='is_kich_hoat',
            field=models.BooleanField(default=True, verbose_name='Đang kích hoạt'),
        ),
        migrations.AddField(
            model_name='nhiemvu',
            name='mo_ta',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả cách thực hiện'),
        ),
        migrations.AddField(
            model_name='nhiemvu',
            name='ten_nhiem_vu',
            field=models.CharField(default='Nhiệm vụ chưa đặt tên', max_length=255, verbose_name='Tên nhiệm vụ'),
        ),
        migrations.AddField(
            model_name='nhiemvu',
            name='xu_thuong',
            field=models.IntegerField(default=10, verbose_name='Xu thưởng'),
        ),
        migrations.AlterField(
            model_name='quatang',
            name='gia_xu',
            field=models.IntegerField(default=100, verbose_name='Giá đổi (Xu)'),
        ),
        migrations.AlterField(
            model_name='quatang',
            name='mau_sac',
            field=models.CharField(default='#F6BCBA', max_length=20, verbose_name='Mã màu UI (Hex)'),
        ),
        migrations.AlterField(
            model_name='quatang',
            name='so_luong_kho',
            field=models.IntegerField(default=10, verbose_name='Số lượng còn'),
        ),
    ]
