# Generated by Django 6.0.3 on 2026-03-12 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyquy', '0006_remove_nhiemvu_da_hoan_thanh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugbounty',
            name='ngay_tao',
        ),
        migrations.RemoveField(
            model_name='phieudexuatchi',
            name='nguoi_duyet',
        ),
        migrations.AddField(
            model_name='bugbounty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 12, 7, 15, 0, 841616, tzinfo=datetime.timezone.utc), verbose_name='Ngày tạo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bugbounty',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)'),
        ),
        migrations.AddField(
            model_name='bugbounty',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm'),
        ),
        migrations.AddField(
            model_name='bugbounty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối'),
        ),
        migrations.AddField(
            model_name='bugbounty',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)'),
        ),
        migrations.AlterField(
            model_name='qatestinglog',
            name='du_lieu_phat_sinh',
            field=models.JSONField(verbose_name='Dữ liệu Data-Seed'),
        ),
        migrations.AlterField(
            model_name='qatestinglog',
            name='loai_test',
            field=models.CharField(max_length=100, verbose_name='Kịch bản giả lập'),
        ),
        migrations.DeleteModel(
            name='BinhLuanKhieuNai',
        ),
    ]
