# Generated by Django 6.0.3 on 2026-03-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyquy', '0007_remove_bugbounty_ngay_tao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secure_pin',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Mã PIN bảo mật (Đã Hash)'),
        ),
    ]
