# Generated by Django 6.0.3 on 2026-03-13 03:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyquy', '0008_user_secure_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='LopHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm')),
                ('ten_lop', models.CharField(max_length=50, verbose_name='Tên lớp')),
                ('nien_khoa', models.CharField(max_length=50, verbose_name='Niên khóa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='giaodich',
            name='dot_thu',
        ),
        migrations.AddField(
            model_name='danhmucthuchi',
            name='mo_ta',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả danh mục'),
        ),
        migrations.AddField(
            model_name='giaodich',
            name='danh_muc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanlyquy.danhmucthuchi', verbose_name='Danh mục'),
        ),
        migrations.AddField(
            model_name='thanhvien',
            name='gender',
            field=models.CharField(choices=[('NAM', 'Nam'), ('NU', 'Nữ')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='thanhvien',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='giaodich',
            name='anh_hoa_don',
            field=models.ImageField(blank=True, null=True, upload_to='hoadon/', verbose_name='Minh chứng (Hóa đơn)'),
        ),
        migrations.AlterField(
            model_name='giaodich',
            name='ly_do',
            field=models.CharField(max_length=255, verbose_name='Nội dung/Ghi chú'),
        ),
        migrations.AlterField(
            model_name='giaodich',
            name='ngay_tao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo giao dịch'),
        ),
        migrations.AddField(
            model_name='thanhvien',
            name='lop_hoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanlyquy.lophoc'),
        ),
    ]
