# Generated by Django 6.0.3 on 2026-03-13 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyquy', '0009_lophoc_remove_giaodich_dot_thu_danhmucthuchi_mo_ta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thanhvien',
            old_name='gender',
            new_name='gioi_tinh',
        ),
        migrations.RenameField(
            model_name='thanhvien',
            old_name='phone',
            new_name='so_dien_thoai',
        ),
    ]
