# Generated by Django 6.0.3 on 2026-03-13 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyquy', '0010_rename_gender_thanhvien_gioi_tinh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thanhvien',
            name='gioi_tinh',
        ),
        migrations.RemoveField(
            model_name='thanhvien',
            name='so_dien_thoai',
        ),
        migrations.AddField(
            model_name='thanhvien',
            name='gender',
            field=models.CharField(choices=[('NAM', 'Nam'), ('NU', 'Nữ')], max_length=10, null=True, verbose_name='Giới tính'),
        ),
        migrations.AddField(
            model_name='thanhvien',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='thanhvien',
            name='lop_hoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanlyquy.lophoc', verbose_name='Lớp học'),
        ),
    ]
