# Generated by Django 6.0.3 on 2026-03-13 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyquy', '0011_remove_thanhvien_gioi_tinh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugbounty',
            name='nguoi_bao_cao',
        ),
        migrations.DeleteModel(
            name='CaiDatHeThong',
        ),
        migrations.RemoveField(
            model_name='hoadonchungtu',
            name='giao_dich',
        ),
        migrations.RemoveField(
            model_name='khoanno',
            name='thanh_vien',
        ),
        migrations.RemoveField(
            model_name='lichsudoiqua',
            name='qua_tang',
        ),
        migrations.RemoveField(
            model_name='lichsudoiqua',
            name='thanh_vien',
        ),
        migrations.RemoveField(
            model_name='luachonbieuquyet',
            name='bieu_quyet',
        ),
        migrations.RemoveField(
            model_name='luotbinhchon',
            name='lua_chon',
        ),
        migrations.RemoveField(
            model_name='luotbinhchon',
            name='bieu_quyet',
        ),
        migrations.RemoveField(
            model_name='luotbinhchon',
            name='thanh_vien',
        ),
        migrations.RemoveField(
            model_name='nhatkyhethong',
            name='nguoi_dung',
        ),
        migrations.RemoveField(
            model_name='thoathuanbaomat',
            name='user',
        ),
        migrations.RemoveField(
            model_name='thongbao',
            name='thanh_vien',
        ),
        migrations.AlterModelOptions(
            name='bieuquyet',
            options={'verbose_name': 'Khảo Sát', 'verbose_name_plural': 'Bầu Cử / Khảo Sát'},
        ),
        migrations.AlterModelOptions(
            name='danhmucthuchi',
            options={'verbose_name': 'Danh Mục', 'verbose_name_plural': 'Danh Mục Thu/Chi'},
        ),
        migrations.AlterModelOptions(
            name='dotthu',
            options={'verbose_name': 'Đợt Thu', 'verbose_name_plural': 'Đợt Thu Tiền'},
        ),
        migrations.AlterModelOptions(
            name='giaodich',
            options={'verbose_name': 'Giao Dịch', 'verbose_name_plural': 'Sổ Giao Dịch'},
        ),
        migrations.AlterModelOptions(
            name='huyhieu',
            options={'verbose_name': 'Huy Hiệu', 'verbose_name_plural': 'Danh Sách Huy Hiệu'},
        ),
        migrations.AlterModelOptions(
            name='huyhieuthanhvien',
            options={'verbose_name': 'Cấp Phát Huy Hiệu', 'verbose_name_plural': 'Lịch Sử Cấp Huy Hiệu'},
        ),
        migrations.AlterModelOptions(
            name='khieunai',
            options={'verbose_name': 'Khiếu Nại', 'verbose_name_plural': 'Quản Lý Khiếu Nại'},
        ),
        migrations.AlterModelOptions(
            name='lichsuwebhook',
            options={'verbose_name': 'Webhook', 'verbose_name_plural': 'Lịch Sử Webhook Auto'},
        ),
        migrations.AlterModelOptions(
            name='loaiquy',
            options={'verbose_name': 'Quỹ Lớp', 'verbose_name_plural': 'Quản Lý Quỹ Lớp'},
        ),
        migrations.AlterModelOptions(
            name='lophoc',
            options={'verbose_name': 'Lớp Học', 'verbose_name_plural': 'Lớp Học'},
        ),
        migrations.AlterModelOptions(
            name='muctieuquy',
            options={'verbose_name': 'Mục Tiêu', 'verbose_name_plural': 'Mục Tiêu Tích Lũy'},
        ),
        migrations.AlterModelOptions(
            name='nhiemvu',
            options={'verbose_name': 'Nhiệm Vụ', 'verbose_name_plural': 'Nhiệm Vụ Tích Xu'},
        ),
        migrations.AlterModelOptions(
            name='phieudexuatchi',
            options={'verbose_name': 'Đề Xuất', 'verbose_name_plural': 'Phiếu Đề Xuất Chi'},
        ),
        migrations.AlterModelOptions(
            name='qatestinglog',
            options={'verbose_name': 'Log QA', 'verbose_name_plural': 'Lịch Sử Test QA'},
        ),
        migrations.AlterModelOptions(
            name='quatang',
            options={'verbose_name': 'Quà Tặng', 'verbose_name_plural': 'Cửa Hàng Quà Tặng'},
        ),
        migrations.AlterModelOptions(
            name='sukiennhacviec',
            options={'verbose_name': 'Sự Kiện', 'verbose_name_plural': 'Sự Kiện & Lịch Trình'},
        ),
        migrations.AlterModelOptions(
            name='taisan',
            options={'verbose_name': 'Tài Sản', 'verbose_name_plural': 'Tài Sản Của Lớp'},
        ),
        migrations.AlterModelOptions(
            name='thanhvien',
            options={'verbose_name': 'Thành Viên', 'verbose_name_plural': 'Hồ Sơ Sinh Viên'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Tài Khoản', 'verbose_name_plural': 'Tài Khoản Hệ Thống'},
        ),
        migrations.RemoveField(
            model_name='nhiemvu',
            name='mo_ta',
        ),
        migrations.RemoveField(
            model_name='quatang',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='quatang',
            name='mau_sac',
        ),
        migrations.RemoveField(
            model_name='quatang',
            name='mo_ta',
        ),
        migrations.AddField(
            model_name='giaodich',
            name='dot_thu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanlyquy.dotthu', verbose_name='Đợt thu'),
        ),
        migrations.AlterField(
            model_name='nhiemvu',
            name='ten_nhiem_vu',
            field=models.CharField(max_length=255, verbose_name='Tên nhiệm vụ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='secure_pin',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Mã PIN bảo mật'),
        ),
        migrations.DeleteModel(
            name='BugBounty',
        ),
        migrations.DeleteModel(
            name='HoaDonChungTu',
        ),
        migrations.DeleteModel(
            name='KhoanNo',
        ),
        migrations.DeleteModel(
            name='LichSuDoiQua',
        ),
        migrations.DeleteModel(
            name='LuaChonBieuQuyet',
        ),
        migrations.DeleteModel(
            name='LuotBinhChon',
        ),
        migrations.DeleteModel(
            name='NhatKyHeThong',
        ),
        migrations.DeleteModel(
            name='ThoaThuanBaoMat',
        ),
        migrations.DeleteModel(
            name='ThongBao',
        ),
    ]
