# Generated by Django 6.0.3 on 2026-03-16 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyquy', '0012_remove_bugbounty_nguoi_bao_cao_delete_caidathethong_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giaodich',
            name='muc_tieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cac_giao_dich', to='quanlyquy.muctieuquy', verbose_name='Thuộc mục tiêu'),
        ),
    ]
