# Generated by Django 6.0.3 on 2026-03-17 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyquy', '0013_giaodich_muc_tieu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nhiemvu',
            options={'verbose_name': 'Nhiệm Vụ', 'verbose_name_plural': '1. Quản Lý Nhiệm Vụ'},
        ),
        migrations.AlterModelOptions(
            name='quatang',
            options={'verbose_name': 'Vật Phẩm Cửa Hàng', 'verbose_name_plural': '3. Cửa Hàng Đặc Quyền'},
        ),
        migrations.RemoveField(
            model_name='nhiemvu',
            name='is_kich_hoat',
        ),
        migrations.RemoveField(
            model_name='nhiemvu',
            name='xu_thuong',
        ),
        migrations.AddField(
            model_name='nhiemvu',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang mở'),
        ),
        migrations.AddField(
            model_name='nhiemvu',
            name='loai_nhiem_vu',
            field=models.CharField(choices=[('AUTO_NOP_QUY', 'Tự động: Đóng quỹ'), ('AUTO_TUONG_TAC', 'Tự động: Tương tác web'), ('MANUAL_ADMIN', 'Thủ công: Admin duyệt')], default='AUTO_NOP_QUY', max_length=20),
        ),
        migrations.AddField(
            model_name='nhiemvu',
            name='mo_ta',
            field=models.TextField(default='', verbose_name='Mô tả & Điều kiện'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nhiemvu',
            name='phan_thuong_xu',
            field=models.IntegerField(default=10, verbose_name='Mức thưởng (Xu)'),
        ),
        migrations.AddField(
            model_name='quatang',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='store/'),
        ),
        migrations.AddField(
            model_name='quatang',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quatang',
            name='loai_qua',
            field=models.CharField(choices=[('VOUCHER', 'Voucher Giảm Quỹ'), ('DAC_QUYEN', 'Thẻ Đặc Quyền'), ('HIEN_VAT', 'Quà Hiện Vật')], default='DAC_QUYEN', max_length=20),
        ),
        migrations.AddField(
            model_name='thanhvien',
            name='tong_xu_tich_luy',
            field=models.IntegerField(default=0, verbose_name='Tổng Xu từng kiếm (Đua TOP)'),
        ),
        migrations.AddField(
            model_name='thanhvien',
            name='vi_xu',
            field=models.IntegerField(default=0, verbose_name='Số dư Xu (Chi tiêu)'),
        ),
        migrations.AlterField(
            model_name='quatang',
            name='gia_xu',
            field=models.IntegerField(verbose_name='Giá bán (Xu)'),
        ),
        migrations.AlterField(
            model_name='quatang',
            name='so_luong_kho',
            field=models.IntegerField(default=10, verbose_name='Tồn kho'),
        ),
        migrations.AlterField(
            model_name='quatang',
            name='ten_qua',
            field=models.CharField(max_length=200, verbose_name='Tên mặt hàng'),
        ),
        migrations.CreateModel(
            name='KhoDoThanhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm')),
                ('trang_thai', models.CharField(choices=[('CHUA_DUNG', 'Chưa sử dụng'), ('DA_DUNG', 'Đã sử dụng')], default='CHUA_DUNG', max_length=20)),
                ('ngay_mua', models.DateTimeField(auto_now_add=True)),
                ('ngay_su_dung', models.DateTimeField(blank=True, null=True)),
                ('qua_tang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlyquy.quatang')),
                ('thanh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kho_do', to='quanlyquy.thanhvien')),
            ],
            options={
                'verbose_name': 'Kho Đồ',
                'verbose_name_plural': '4. Kho Đồ Thành Viên',
            },
        ),
        migrations.CreateModel(
            name='LichSuGiaoDichXu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm')),
                ('loai_giao_dich', models.CharField(choices=[('CONG_XU', 'Cộng Xu (+)'), ('TRU_XU', 'Tiêu Xu (-)')], max_length=10)),
                ('so_xu', models.IntegerField(verbose_name='Số lượng Xu (+/-)')),
                ('ly_do', models.CharField(max_length=255, verbose_name='Lý do (Làm NV gì / Mua gì)')),
                ('ngay_thuc_hien', models.DateTimeField(auto_now_add=True)),
                ('nhiem_vu_lien_quan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanlyquy.nhiemvu')),
                ('thanh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_xu', to='quanlyquy.thanhvien')),
            ],
            options={
                'verbose_name': 'Giao Dịch Xu',
                'verbose_name_plural': '2. Lịch Sử Biến Động Xu',
            },
        ),
    ]
