# Generated by Django 6.0.3 on 2026-03-19 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyquy', '0014_alter_nhiemvu_options_alter_quatang_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongBaoBuuTa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm')),
                ('tieu_de', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('noi_dung', models.TextField(verbose_name='Nội dung chi tiết')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc?')),
                ('link_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link liên kết')),
                ('loai', models.CharField(choices=[('SYSTEM', '⚡ Hệ thống'), ('REMIND', '📢 Nhắc nợ'), ('FINANCE', '💰 Tài chính')], default='SYSTEM', max_length=20, verbose_name='Phân loại')),
                ('nguoi_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thong_bao_receivers', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận')),
            ],
            options={
                'verbose_name': 'Bưu tá Hệ thống',
                'verbose_name_plural': 'Bưu tá Hệ thống',
            },
        ),
    ]
