# Generated by Django 6.0.3 on 2026-03-20 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyquy', '0015_thongbaobuuta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhuongAnBieuQuyet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm')),
                ('noi_dung', models.CharField(max_length=255, verbose_name='Nội dung phương án (VD: Đi Vũng Tàu)')),
                ('luot_chon', models.IntegerField(default=0, verbose_name='Số người đã vote')),
                ('bieu_quyet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_phuong_an', to='quanlyquy.bieuquyet')),
            ],
            options={
                'verbose_name': 'Phương Án',
                'verbose_name_plural': 'Các Phương Án',
            },
        ),
    ]
