# Generated by Django 6.0.3 on 2026-03-20 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyquy', '0016_phuonganbieuquyet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietBinhChon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm')),
                ('bieu_quyet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlyquy.bieuquyet')),
                ('phuong_an', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlyquy.phuonganbieuquyet')),
                ('thanh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlyquy.thanhvien')),
            ],
            options={
                'verbose_name': 'Chi tiết Vote',
                'verbose_name_plural': 'Lịch sử Vote chi tiết',
                'unique_together': {('bieu_quyet', 'thanh_vien')},
            },
        ),
    ]
